# Content
1. [Quantifying The Future](#Quantifying-The-Future)
2. [Supporting Research](#Supporting-Research)
3. [Background](#Background)
4. [Problem Statement](#Problem-Statement)
5. [Intended Audience](#Intended-Audience)
6. [Approach & Measure of Success](#Approach-&-Measure-of-Success)
7. [Data Dictionary](#Data-Dictionary)
8. [Library Dictionary](#Library-Dictionary)
9. [Data Inspection & Cleaning](#Data-Inspection-&-Cleaning)
10. [End of Notebook](#End-of-Notebook)

Feel free to click on the following notebooks to 'fast forward' to other sections of this project.

|Notebook Title|Description|
|---|---|
|[01_Intro_Data_Cleaning](01_Intro_Data_Cleaning.ipynb)|This notebook contains the introduction of the project, background motivation, problem statement and the inspection and cleaning of data.|

# Quantifying The Future

In this project, I will be attempting to predict future US GDP in order to reasonably quantify the future global economic growth in order to make better investment decisions today.

I will be predicting future US GDP on a percentage basis, relative to its prior reading. This is so because the absolute figure for GDP is irrelevant when using future US GDP as a risk management tool. What the stakeholder would be interested in would be whether GDP is growing, slowing or shrinking, relative to its prior reading and not how large it is in dollar terms.

# Supporting Research

You may find a list of supporting research used for this project here:

1. [TATA Group Invests in Gigafactory in the UK]((https://www.cnbc.com/2023/07/19/indias-tata-group-to-build-5-billion-gigafactory-in-the-uk.html))
2. [Is the World Economy Dependent on America?](https://www.managementstudyguide.com/world-economy-dependent-on-america.htm)
3. [EU & US trade](https://www.eeas.europa.eu/united-states-america/european-union-and-united-states_en?s=253#:~:text=Deep%20Economic%20Ties,-The%20EU%2DUS&text=The%20EU%20and%20the%20United%20States%20are%20each%20other's%20main,investment%20markets%20of%20first%20choice.)
4. [Singapore's Top Trading Partners](https://www.singstat.gov.sg/modules/infographics/singapore-international-trade#:~:text=In%202022%2C%20Mainland%20China%2C%20Malaysia,exports%20to%20these%20trading%20partners.)

# Background

## Invest + Risk Management

Investing is a difficult task to carry out successfully. On a personal level, I feel that the term 'investing' is somewhat of a misnomer by itself. Although the act of investing involves an entity to utilise capital in order to realise a favorable future outcome, hence the term 'invest', the primary factor that determines the success of an investment is how well its associated risks are defined and managed. Investing for a favorable future outcome requires rigorous risk management.

There are many uncertainties or risks that needs to be understood on a detailed level and if the investor fails to understand these risks and account for them, they may be setting themselves up for a failed investing endeavor even before they begin.

One of the most fundamental risk that an investor or steward of capital needs to appreciate is future demand or future economic growth. If the CEO of an automobile company or the Chief Investing Officer of a hedge fund decides to invest significant sums of money to expand their business or to invest in a target company, he or she needs to be able to appreciate that at a fundamental level, there must growing economic demand to support the basis for expansion or investment.

## Predicting US GDP For All Stakeholders

Investing does not need to be restricted in its definition in the sense where an invester invests in financial markets through financial securities such as equities or fixed income assets. An investment can also come in the form of capital expenditure, factory expansions, hiring of employees etc.

Investing today to achieve an envisioned future outcome is a difficult task to accomplish across sectors or industries. An applicable example is when an Indian multi national corporation, TATA group, making the [decision](https://www.cnbc.com/2023/07/19/indias-tata-group-to-build-5-billion-gigafactory-in-the-uk.html) to invest in UK and build a $5 billion gigafactory there, one of Europe's largest.

One of the very basic questions that needs to be answered in this example is 'Would Europeans demand to purchase more electric vehicles increase, and in turn drive increased demand for more batteries produced from their invested gigafactory?'. The answer to the question is very much rooted in whether people would be able to afford to buy an electric vehicle in the future and that very much depends on whether their economic prospects are secure and growing. If we are able to understand on a very fundamental level that the average European is looking forward to growing and rising economic prospects, then it is reasonable to say that the average European would then be able to afford and purchase an electric vehicle, driving increased demand for the batteries the gigafactory produces, all else being equal.

Such insights can be a powerful tool to establish a fundamental baseline of what to expect economically in the future. 

In a counter example, one can then come to the conclusion that if the [US economy (GDP) and by extension a significant part of the world's economy](https://www.managementstudyguide.com/world-economy-dependent-on-america.htm) is predicted to weaken significantly, it would not make sense for TATA group to invest $5 Billion in a gigafactory in the UK. Postponing the project or re-pricing it for lower input costs while waiting for projected economic growth would make much more sense than investing into a global economy with weakening demand. 

## US Economy Drives Global Growth, Including Singapore

The relationship between Europe and US GDP are apparent because [The EU and the United States are each otherâ€™s main trading partners and account for the largest bilateral trade relationship in the world](https://www.eeas.europa.eu/united-states-america/european-union-and-united-states_en?s=253#:~:text=Deep%20Economic%20Ties,-The%20EU%2DUS&text=The%20EU%20and%20the%20United%20States%20are%20each%20other's%20main,investment%20markets%20of%20first%20choice.) This dynamic also ring true for countries that are [highly dependend on international trade and have the US as a major trading partner](https://www.singstat.gov.sg/modules/infographics/singapore-international-trade#:~:text=In%202022%2C%20Mainland%20China%2C%20Malaysia,exports%20to%20these%20trading%20partners.), such as Singapore. Singapore trades with many countries that depends on the financial system administered by the US and directly depend on US demand for exports and economic growth (GDP). Therefore, if the US is forecasted to have lower or negative GDP growth, Singapore and most of her trading partners will be expected to have lower or negative GDP growth in their respective economies too. In short, many economies like Singapore behaves as a reactive function to the US Economy.

Therefore, in order to empower investment decision makers across regions, functions and industries, I aim to predict the most fundamental and prevalent precursor for demand, US GDP. By doing so, these stakeholders can quantify future demand and help them make better investment decisions today.

# Problem Statement

By predicting future US GDP, I am able to quantify future demand outlook for my stakeholders and enable them to make better investment and risk management decisions today.

# Intended Audience

The intended audience for this project is for investment decision makers across industries and applicable regions. This could be in the form of the following examples:

- CEOs
- Hiring managers
- CAPEX managers
- Stewards of Capital
- CIOs
- Portfolio managers
- Retail Investors
- etc

# Approach & Measure of Success

I will be modeling US GDP to predict future values by utilising the following Machine Learning algorithms:

1. ARIMA and its extensions
2. Regression
3. DARTS
4. BATS
5. TBATS
6. Pycaret
7. Prophet

In my approach, I will be using ARIMA (without extensions) as a baseline model and I will work my way through all the other models to compare its predicitive performance against the baseline.

I will be using MAPE (Mean Absolute Percentage Error) to determine which model would be the most accurate over the same training and validation timeframe. After the best selected model is chosen, I will conduct further experiments to determine the limits of the model to determine how far into the future the model could predict and draw conclusions from there.

# Data Features & Sources

As I will be predicting GDP on a % increase or decrease vs its prior period, the data that I will be extracting and modeling upon would be in similar percentage difference terms.

Further, as the focus of this project is to predict GDP before actual GDP numbers are released, I will be focusing on aggregating monthly variables to quarterly periods for the machine learning algorithms to model. While my ultimate intention is to predict GDP before GDP numbers are released, as a baseline, these features must prove its relevance in a time series solution in quarterly periods first before adjustments are made to its periods.

|Feature|Frequency|Period|Description|Source|
|---|---|---|---|---|
|GDP|Q|1947 - 2023|Gross domestic product is the monetary value of all finished goods and services made within a country during a specific period|[BEA](https://apps.bea.gov/)|
|Monthly GDP Index|M|1992 - 2023|Monthly GDP (MGDP) Index is an indicator of real aggregate output that is conceptually consistent with real Gross Domestic Product (GDP) in the National Income and Product Accounts (NIPA)|[S&P Global Market Intelligence](https://www.spglobal.com/)|
|PCE|M|1959 - 2023|Personal consumption expenditures is a measure of consumer spending|[BEA](https://apps.bea.gov/)|
|Industrial Production|M|1919-2023|Industrial production cover output, capacity, and capacity utilization in the U.S. industrial sector, which is defined by the Federal Reserve to comprise manufacturing, mining, and electric and gas utilities|[Federal Reserve Board](https://www.federalreserve.gov/)|
|Aggregate Weekly Payrolls|M|2006-2023|Aggregate payrolls represents the earnings by all employed people, either full- or part-time|[US Department of Labor](https://beta.bls.gov/)|
|Aggregate Weekly Hours Worked|M|2006-2023|Aggregate weekly hours worked represents the hours worked by all employed people, either full - or part-time|[US Department of Labor](https://beta.bls.gov)
|Exports|M|1960 - 2023|Total US Exports|[BEA](https://apps.bea.gov/)|
|Headline Retail Sales|M|1992 - 2023|Retail sales are an economic metric that tracks consumer demand for finished goods|[US Census Bureau](https://www.census.gov/)|
|Total Employees on Nonfarm Payrolls|M|1939 - 2023|The nonfarm payroll measures the number of workers in the U.S. except those in farming, private households, proprietors, non-profit employees, and active military|[US Department of Labor](https://beta.bls.gov/)|
|Imports of Goods and Services|M|1992 - 2023|Total US Imports|[St. Louis Fed](https://fred.stlouisfed.org/)|
|Manufacturers New Orders|M|1992 - 2023|Manufacturers new orders are economic indicators, meaning they signify an overall direction of the market and economy. When factory orders increase, it usually means the economy is expanding as consumers demand more goods and services, which in turn requires retailers and suppliers to order more supplies from factories.|[St. Louis Fed](https://fred.stlouisfed.org/)|
|University of Michigan Consumer Sentiment Index|M|1978 - 2003|Factory orders are economic indicators, meaning they signify an overall direction of the market and economy. When factory orders increase, it usually means the economy is expanding as consumers demand more goods and services, which in turn requires retailers and suppliers to order more supplies from factories|[University of Michigan](https://data.sca.isr.umich.edu/)|
|Leading Indicators OECD|M|1960 - 2023|The OECD system of composite leading indicators is designed to give early signals of turning-points in economic activity|[St. Louis Fed](https://fred.stlouisfed.org/)|

# Data Dictionary

Please find a list of features and its description here.

|Feature Name|Brief Description|
|--|--|

# Module Dictionary

Here is a summary of the functions and a brief description of what they do which I may call upon from zul_modules.

|Name|Brief Description|
|---|---|
|data_inspector(df)|Checks dataframe and returns shape, dtypes, sum of null values, and head|
|quick_check(df)|Returns shape and head|

# Libraries Used

In [1]:
import pandas as pd
import zul_module as zm

In [2]:
# To see all rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
# To turn off:
#pd.reset_option('display.max_rows')
#pd.reset_option('display.max_columns')

# Data Inspection & Cleaning

In this section, I will be reading in the datasets for inspection, cleaning and formatting.

##### Methodology

1. Formatting for columns / rows
2. Create columns to reflect arbitrary date to reflect end of period the datapoint is reporting on
3. Define dataframe to contain only datapoitns of interest
4. Check for null values, correct dtypes, duplicates
5. Repeat for all other datasets
6. Combine to dataframes of interest
7. Export to assets folder

## Quarterly GDP

In [3]:
# Read in data
gdp_q = pd.read_csv('../data/gdp_qq.csv')

In [4]:
zm.quick_check(gdp_q)

The shape is (29, 307).

,Unnamed: 0,Year,1947,1947.1,1947.2,1948,1948.1,1948.2,1948.3,1949,1949.1,1949.2,1949.3,1950,1950.1,1950.2,1950.3,1951,1951.1,1951.2,1951.3,1952,1952.1,1952.2,1952.3,1953,1953.1,1953.2,1953.3,1954,1954.1,1954.2,1954.3,1955,1955.1,1955.2,1955.3,1956,1956.1,1956.2,1956.3,1957,1957.1,1957.2,1957.3,1958,1958.1,1958.2,1958.3,1959,1959.1,1959.2,1959.3,1960,1960.1,1960.2,1960.3,1961,1961.1,1961.2,1961.3,1962,1962.1,1962.2,1962.3,1963,1963.1,1963.2,1963.3,1964,1964.1,1964.2,1964.3,1965,1965.1,1965.2,1965.3,1966,1966.1,1966.2,1966.3,1967,1967.1,1967.2,1967.3,1968,1968.1,1968.2,1968.3,1969,1969.1,1969.2,1969.3,1970,1970.1,1970.2,1970.3,1971,1971.1,1971.2,1971.3,1972,1972.1,1972.2,1972.3,1973,1973.1,1973.2,1973.3,1974,1974.1,1974.2,1974.3,1975,1975.1,1975.2,1975.3,1976,1976.1,1976.2,1976.3,1977,1977.1,1977.2,1977.3,1978,1978.1,1978.2,1978.3,1979,1979.1,1979.2,1979.3,1980,1980.1,1980.2,1980.3,1981,1981.1,1981.2,1981.3,1982,1982.1,1982.2,1982.3,1983,1983.1,1983.2,1983.3,1984,1984.1,1984.2,1984.3,1985,1985.1,1985.2,1985.3,1986,1986.1,1986.2,1986.3,1987,1987.1,1987.2,1987.3,1988,1988.1,1988.2,1988.3,1989,1989.1,1989.2,1989.3,1990,1990.1,1990.2,1990.3,1991,1991.1,1991.2,1991.3,1992,1992.1,1992.2,1992.3,1993,1993.1,1993.2,1993.3,1994,1994.1,1994.2,1994.3,1995,1995.1,1995.2,1995.3,1996,1996.1,1996.2,1996.3,1997,1997.1,1997.2,1997.3,1998,1998.1,1998.2,1998.3,1999,1999.1,1999.2,1999.3,2000,2000.1,2000.2,2000.3,2001,2001.1,2001.2,2001.3,2002,2002.1,2002.2,2002.3,2003,2003.1,2003.2,2003.3,2004,2004.1,2004.2,2004.3,2005,2005.1,2005.2,2005.3,2006,2006.1,2006.2,2006.3,2007,2007.1,2007.2,2007.3,2008,2008.1,2008.2,2008.3,2009,2009.1,2009.2,2009.3,2010,2010.1,2010.2,2010.3,2011,2011.1,2011.2,2011.3,2012,2012.1,2012.2,2012.3,2013,2013.1,2013.2,2013.3,2014,2014.1,2014.2,2014.3,2015,2015.1,2015.2,2015.3,2016,2016.1,2016.2,2016.3,2017,2017.1,2017.2,2017.3,2018,2018.1,2018.2,2018.3,2019,2019.1,2019.2,2019.3,2020,2020.1,2020.2,2020.3,2021,2021.1,2021.2,2021.3,2022,2022.1,2022.2,2022.3,2023,2023.1
0,NaN,Quarter,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2
1,1.0,Gross domestic product,-1.1,-0.8,6.4,6.2,6.8,2.3,0.5,-5.4,-1.4,4.2,-3.3,16.6,12.8,16.4,7.9,5.5,7.1,8.5,0.9,4.3,0.9,2.9,13.8,7.6,3.1,-2.2,-5.9,-1.9,0.4,4.6,8.1,11.9,6.6,5.5,2.4,-1.5,3.3,-0.4,6.8,2.6,-0.9,4,-4.1,-10,2.6,9.6,9.7,7.9,9.3,0.3,1.1,9.3,-2.1,2,-5,2.7,7,7.9,8.1,7.3,3.7,5,1.3,4.4,4.6,9.1,2.7,8.7,4.4,6.4,1.2,10,5.2,9.2,9.5,10.1,1.4,3.4,3.3,3.6,0.3,3.8,3.1,8.4,6.9,3.1,1.6,6.4,1.2,2.7,-1.9,-0.6,0.6,3.7,-4.2,11.3,2.2,3.3,1,7.6,9.4,3.8,6.9,10.3,4.4,-2.1,3.9,-3.4,1,-3.7,-1.5,-4.8,2.9,7,5.5,9.3,3,2.2,2.9,4.8,8,7.4,0,1.3,16.4,4.1,5.5,0.7,0.4,3,1,1.3,-8,-0.5,7.7,8.1,-2.9,4.9,-4.3,-6.1,1.8,-1.5,0.2,5.4,9.4,8.2,8.6,8.1,7.1,3.9,3.3,3.9,3.6,6.2,3,3.8,1.8,3.9,2.2,3,4.4,3.5,7,2.1,5.4,2.4,5.4,4.1,3.1,3,0.8,4.4,1.5,0.3,-3.6,-1.9,3.2,2,1.4,4.9,4.4,4,4.2,0.7,2.3,1.9,5.5,3.9,5.5,2.4,4.7,1.4,1.2,3.4,2.7,3,6.8,3.6,4.2,2.6,6.8,5.1,3.5,4.1,3.8,5.1,6.6,3.8,3.4,5.4,6.7,1.5,7.5,0.4,2.4,-1.3,2.5,-1.6,1.1,3.4,2.5,1.6,0.5,2.1,3.6,6.8,4.7,2.3,3.2,3.8,4.2,4.5,2,3.2,2.3,5.5,1,0.6,3.4,1.2,2.6,2.4,2.5,-1.6,2.3,-2.1,-8.5,-4.6,-0.7,1.5,4.3,2,3.9,3.1,2.1,-1,2.7,-0.2,4.6,3.3,1.8,0.7,0.4,3.5,0.6,3.2,2.9,-1.4,5.2,4.7,1.8,3.3,2.3,1.3,0.6,2.4,1.2,2.4,2,1.7,2,3.4,4.1,2.8,2.8,2.9,0.7,2.2,2.7,3.6,1.8,-4.6,-29.9,35.3,3.9,6.3,7,2.7,7,-1.6,-0.6,3.2,2.6,2,2.4
2,2.0,Personal consumption expenditures,6.8,1.3,0.1,2,4.7,0.6,3.2,0.7,6.3,0.9,6,6.8,6.8,22.2,-11.5,10,-10.8,4.7,2.4,0.9,8.1,1.9,14.9,4.8,2.4,-1,-2.6,1.5,5.3,5.5,8.7,9.3,7.9,5,5.1,0.6,1.3,0.9,5.6,2.8,0.7,3.2,0.1,-5.4,3.3,6.8,5.6,7.5,6.3,4.2,0.5,3.9,5.1,-1.6,0.5,-0.2,6.1,2,8.3,4.3,5,3.3,5.8,2.8,3.8,5.5,3.4,8.1,7.3,7.6,1.1,9.2,4.5,7,11.7,6,1,4.7,1.7,2.3,5.6,2.1,2.5,9.9,6.2,7.7,1.8,4.5,2.6,2,3.2,2.5,1.8,3.6,-1.1,7.9,3.7,3.2,6.8,5.4,7.8,6.3,9.7,7.5,-0.2,1.4,-1.2,-3.5,1.4,1.7,-5.7,3.4,6.7,5.8,4.4,8.2,3.7,4.3,5.3,4.8,2.2,3.8,6.1,2.3,8.8,1.7,3.3,2.1,-0.3,3.9,1,-0.6,-8.7,4.5,5.5,1.3,0,1.9,-2.7,3,1.2,2.7,7.2,4,8.4,7.4,6.5,3.4,5.7,3,5.3,7,3.7,7.8,0.9,3.5,4.4,7.3,2.5,0.4,5.6,4.6,0.8,7.3,3,3.6,4.6,1.9,1.9,3.9,1.8,3.4,1.2,1.6,-3,-1.5,3.4,2,-0.2,7.7,2.7,4.4,4.8,1.5,3.7,4.5,3.6,4.7,3.1,3.1,4.4,1,3.6,3.7,2.8,3.7,4.4,2.4,3.2,4.3,1.8,7,4.9,4.1,7.2,5.3,5.9,4.2,6.3,4.6,6,6.2,3.8,3.9,3.5,1.5,0.8,1.4,6.6,0.9,2,2.8,2.2,2,4.7,5.8,2.8,3.8,2.2,4.8,4.6,2.6,4.5,3.4,0.7,4.4,2.1,2.6,3.9,2.5,1.1,2.7,1.6,-0.5,1.1,-3,-3.6,-1,-2,2.7,-0.4,2.3,3.6,2.9,2.5,1.5,0.4,1.2,0.7,2.9,0.7,0.8,1.6,2.1,0.6,1.5,3.2,1.5,3.8,4,4.5,2.7,2.7,3.1,2,3,2,2.4,2,2.9,1.6,2.4,4.4,2.7,2.9,2.6,1.8,0.4,2.6,3.4,2.4,-6.2,-32.1,43,3.9,10.8,12.1,3,3.1,1.3,2,2.3,1,4.2,1.6
3,3.0,Goods,7.4,2.7,1.5,0.6,3.7,-0.4,2.7,-0.6,9.1,2.1,9.2,8,4.3,33.5,-19.5,9.1,-18.8,4.5,3.3,-1.9,9.3,-0.4,21.8,5.4,0.8,-3.3,-2.4,-0.2,4,4.3,11.6,12.9,11.7,5.7,2.9,-1.8,-0.6,-1.7,5.9,3.8,-1.4,3.4,-3.1,-9.2,1.2,7.8,8,9.6,6.5,3.2,-3.2,4.1,5.7,-2.5,-2.4,-3.7,6.2,2.6,9.2,4.8,4,3.1,6.4,3.8,3.4,4.1,1.4,9.6,8.7,9.7,-2.9,13.7,2.9,8.4,16.3,7.7,-2,5.9,-0.8,1,7.2,-1.2,1.6,13.4,6.1,10.2,-0.7,5.5,0.3,0.7,1.4,0.6,1.1,2.5,-4.3,13.5,3.3,2.6,7.2,3.8,11,7.1,12.3,9.9,-3.8,0.1,-3.9,-6.4,-1.2,1.3,-15.3,2.9,8.8,10.2,2.8,12.2,4.9,3.6,5,4.5,3,3.3,8.8,-2.2,12,0.3,4.6,-0.3,-3.3,6.8,-1.7,-2,-15.5,4.2,4.6,5.9,-3.2,4.1,-7,4.1,-0.1,2.1,8.3,2.1,12.3,9.2,9.8,5.5,9.2,0.3,6.4,6.3,3.7,11.1,-2.4,6.2,7.3,13,-0.3,-7.9,7.9,6.2,-3.5,9.8,2.1,-0.1,6.5,0.5,2.3,5.9,-1.3,5.5,-4.2,-0.9,-6.2,-3.4,2.3,2.4,-4.4,9.4,2,4.4,5.4,1.6,6.6,4.2,5.2,6.9,3.6,3.8,7.9,-2,2.7,4.9,3.8,3.2,8,2.9,4.9,5.5,-0.3,10.8,5.6,3,10.8,6.1,12.7,5,9.8,4.8,7,6.1,2.1,4.2,3.5,0.9,1.1,2.9,15.2,-0.7,1.1,5,1.6,2.2,9,11.7,3.6,4.6,1.4,5.7,5.5,3.1,6,3.9,-0.8,8.5,0.6,3.6,5.7,2.8,0.9,2.5,0.8,-6.4,-0.6,-8.1,-11.6,0.1,-2.5,7.2,-2.1,3,5.6,3,5.7,2,-1.5,0.1,2.9,5.2,-0.1,1.8,2.9,7.1,0.3,2.9,3.8,2.7,7.4,4.7,5.5,4.9,4.3,4.6,1.6,4.1,3.5,4,2.2,3.3,4.2,4.7,8.7,1.1,3.1,3.4,3.3,0,5.5,5.8,2.8,0,-10.7,55.2,0.3,25.3,11.6,-7.9,2.3,-0.1,-2.6,-0.4,-0.1,6,0.7
4,4.0,Durable goods,8.7,5.6,28.6,-2,2.7,7,-5.5,-7.1,39.4,20.5,16.8,16.2,3.5,134.1,-41,13.2,-46.2,-7,-1.3,2.3,8.1,-21.7,88.9,14.1,-2.3,-2.5,-10.7,-11.8,20.8,1.7,26.9,41.1,23.5,13.6,-10.1,-17.1,0.5,-6.9,13.5,7.5,-9.1,-2.7,-4.6,-24.1,-6,8.6,15.4,23.6,15.9,7.9,-17.8,13.5,9.4,-3.1,-9.7,-20.2,8.6,10.1,20.9,8.9,11.2,2.9,18.8,8.2,8.9,5,6.5,16.5,10.8,13.9,-11.7,42.8,0.6,14.4,18,20.4,-15,13.8,-0.1,-7.4,18.4,-3.2,1,27.3,8.8,19.3,-2.3,7.7,-1.1,-1.1,-1.5,-6,4.7,1.5,-24,50.3,9.4,11.1,18.2,9.5,10.5,10.7,22.9,28,-4.6,-3.5,-9,-9,2.2,2.3,-33,8.8,8,27.4,12.2,21.5,1.8,4.6,6.5,16,9.8,6,8.7,-10.2,33.3,-5.3,3.2,-4.6,-8.7,11.6,-9.9,-6.1,-36.7,19,12.7,11.9,-14.7,12.7,-25.8,13.4,1.5,3.3,19.6,4.1,32.5,16.3,21.2,16,9.6,0.1,13.6,14.6,4.8,28.2,-13.1,8.4,14.9,38.7,-6.2,-21.7,17.4,17.6,-10.4,20.3,0.1,-5.1,10.8,-1.8,5.4,9.4,-11.6,18,-12.6,-4,-10.6,-10.6,2,6.3,-6.4,16.7,2.8,8.8,8.2,3.9,13.6,4.5,10,9.9,4.4,4.3,14.8,-8,4.1,11.8,7.1,4.4,13.3,2.9,8,11.3,-1.3,19,10.6,3.3,21.8,11.8,25.8,0.9,20.5,9.9,4.9,24.3,-7.2,7,2.8,6.7,-0.3,4.7,37.7,-4.3,2.5,12.5,-3.6,0.4,19.4,18.9,5.9,7.2,1,10.7,7.8,1.9,11.1,8.1,-11.4,16.9,0.2,5.9,5.8,5.5,4.3,5,3,-12.3,-2.8,-12.8,-26.3,0.7,-2.9,20.9,-9.1,5,13.2,6.4,11.7,3.5,-2.8,3.6,9.9,10.1,0.8,5.3,9.4,10.7,1.8,3.4,4.4,6.5,15.2,7.5,7.8,7.4,8.7,5.5,2.3,5.3,4,10.4,5.7,2.5,4.6,10.6,15.8,2.5,5.5,5,1.7,-3.5,8.9,10.3,7.7,-11.3,0.4,103.6,0.6,44.7,10.6,-22,5.1,7.6,-2.8,-0.8,-1.3,16.3,0.4

In [5]:
# Drop 'Line' Column & Reset index to 'Year' to transpose on the correct axis.
gdp_q.drop(columns='Unnamed: 0', inplace=True)
gdp_q.set_index('Year', inplace=True)

# Inspect
gdp_q.head()

,1947,1947.1,1947.2,1948,1948.1,1948.2,1948.3,1949,1949.1,1949.2,1949.3,1950,1950.1,1950.2,1950.3,1951,1951.1,1951.2,1951.3,1952,1952.1,1952.2,1952.3,1953,1953.1,1953.2,1953.3,1954,1954.1,1954.2,1954.3,1955,1955.1,1955.2,1955.3,1956,1956.1,1956.2,1956.3,1957,1957.1,1957.2,1957.3,1958,1958.1,1958.2,1958.3,1959,1959.1,1959.2,1959.3,1960,1960.1,1960.2,1960.3,1961,1961.1,1961.2,1961.3,1962,1962.1,1962.2,1962.3,1963,1963.1,1963.2,1963.3,1964,1964.1,1964.2,1964.3,1965,1965.1,1965.2,1965.3,1966,1966.1,1966.2,1966.3,1967,1967.1,1967.2,1967.3,1968,1968.1,1968.2,1968.3,1969,1969.1,1969.2,1969.3,1970,1970.1,1970.2,1970.3,1971,1971.1,1971.2,1971.3,1972,1972.1,1972.2,1972.3,1973,1973.1,1973.2,1973.3,1974,1974.1,1974.2,1974.3,1975,1975.1,1975.2,1975.3,1976,1976.1,1976.2,1976.3,1977,1977.1,1977.2,1977.3,1978,1978.1,1978.2,1978.3,1979,1979.1,1979.2,1979.3,1980,1980.1,1980.2,1980.3,1981,1981.1,1981.2,1981.3,1982,1982.1,1982.2,1982.3,1983,1983.1,1983.2,1983.3,1984,1984.1,1984.2,1984.3,1985,1985.1,1985.2,1985.3,1986,1986.1,1986.2,1986.3,1987,1987.1,1987.2,1987.3,1988,1988.1,1988.2,1988.3,1989,1989.1,1989.2,1989.3,1990,1990.1,1990.2,1990.3,1991,1991.1,1991.2,1991.3,1992,1992.1,1992.2,1992.3,1993,1993.1,1993.2,1993.3,1994,1994.1,1994.2,1994.3,1995,1995.1,1995.2,1995.3,1996,1996.1,1996.2,1996.3,1997,1997.1,1997.2,1997.3,1998,1998.1,1998.2,1998.3,1999,1999.1,1999.2,1999.3,2000,2000.1,2000.2,2000.3,2001,2001.1,2001.2,2001.3,2002,2002.1,2002.2,2002.3,2003,2003.1,2003.2,2003.3,2004,2004.1,2004.2,2004.3,2005,2005.1,2005.2,2005.3,2006,2006.1,2006.2,2006.3,2007,2007.1,2007.2,2007.3,2008,2008.1,2008.2,2008.3,2009,2009.1,2009.2,2009.3,2010,2010.1,2010.2,2010.3,2011,2011.1,2011.2,2011.3,2012,2012.1,2012.2,2012.3,2013,2013.1,2013.2,2013.3,2014,2014.1,2014.2,2014.3,2015,2015.1,2015.2,2015.3,2016,2016.1,2016.2,2016.3,2017,2017.1,2017.2,2017.3,2018,2018.1,2018.2,2018.3,2019,2019.1,2019.2,2019.3,2020,2020.1,2020.2,2020.3,2021,2021.1,2021.2,2021.3,2022,2022.1,2022.2,2022.3,2023,2023.1
Year,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Quarter,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2
Gross domestic product,-1.1,-0.8,6.4,6.2,6.8,2.3,0.5,-5.4,-1.4,4.2,-3.3,16.6,12.8,16.4,7.9,5.5,7.1,8.5,0.9,4.3,0.9,2.9,13.8,7.6,3.1,-2.2,-5.9,-1.9,0.4,4.6,8.1,11.9,6.6,5.5,2.4,-1.5,3.3,-0.4,6.8,2.6,-0.9,4,-4.1,-10,2.6,9.6,9.7,7.9,9.3,0.3,1.1,9.3,-2.1,2,-5,2.7,7,7.9,8.1,7.3,3.7,5,1.3,4.4,4.6,9.1,2.7,8.7,4.4,6.4,1.2,10,5.2,9.2,9.5,10.1,1.4,3.4,3.3,3.6,0.3,3.8,3.1,8.4,6.9,3.1,1.6,6.4,1.2,2.7,-1.9,-0.6,0.6,3.7,-4.2,11.3,2.2,3.3,1,7.6,9.4,3.8,6.9,10.3,4.4,-2.1,3.9,-3.4,1,-3.7,-1.5,-4.8,2.9,7,5.5,9.3,3,2.2,2.9,4.8,8,7.4,0,1.3,16.4,4.1,5.5,0.7,0.4,3,1,1.3,-8,-0.5,7.7,8.1,-2.9,4.9,-4.3,-6.1,1.8,-1.5,0.2,5.4,9.4,8.2,8.6,8.1,7.1,3.9,3.3,3.9,3.6,6.2,3,3.8,1.8,3.9,2.2,3,4.4,3.5,7,2.1,5.4,2.4,5.4,4.1,3.1,3,0.8,4.4,1.5,0.3,-3.6,-1.9,3.2,2,1.4,4.9,4.4,4,4.2,0.7,2.3,1.9,5.5,3.9,5.5,2.4,4.7,1.4,1.2,3.4,2.7,3,6.8,3.6,4.2,2.6,6.8,5.1,3.5,4.1,3.8,5.1,6.6,3.8,3.4,5.4,6.7,1.5,7.5,0.4,2.4,-1.3,2.5,-1.6,1.1,3.4,2.5,1.6,0.5,2.1,3.6,6.8,4.7,2.3,3.2,3.8,4.2,4.5,2,3.2,2.3,5.5,1,0.6,3.4,1.2,2.6,2.4,2.5,-1.6,2.3,-2.1,-8.5,-4.6,-0.7,1.5,4.3,2,3.9,3.1,2.1,-1,2.7,-0.2,4.6,3.3,1.8,0.7,0.4,3.5,0.6,3.2,2.9,-1.4,5.2,4.7,1.8,3.3,2.3,1.3,0.6,2.4,1.2,2.4,2,1.7,2,3.4,4.1,2.8,2.8,2.9,0.7,2.2,2.7,3.6,1.8,-4.6,-29.9,35.3,3.9,6.3,7,2.7,7,-1.6,-0.6,3.2,2.6,2,2.4
Personal consumption expenditures,6.8,1.3,0.1,2,4.7,0.6,3.2,0.7,6.3,0.9,6,6.8,6.8,22.2,-11.5,10,-10.8,4.7,2.4,0.9,8.1,1.9,14.9,4.8,2.4,-1,-2.6,1.5,5.3,5.5,8.7,9.3,7.9,5,5.1,0.6,1.3,0.9,5.6,2.8,0.7,3.2,0.1,-5.4,3.3,6.8,5.6,7.5,6.3,4.2,0.5,3.9,5.1,-1.6,0.5,-0.2,6.1,2,8.3,4.3,5,3.3,5.8,2.8,3.8,5.5,3.4,8.1,7.3,7.6,1.1,9.2,4.5,7,11.7,6,1,4.7,1.7,2.3,5.6,2.1,2.5,9.9,6.2,7.7,1.8,4.5,2.6,2,3.2,2.5,1.8,3.6,-1.1,7.9,3.7,3.2,6.8,5.4,7.8,6.3,9.7,7.5,-0.2,1.4,-1.2,-3.5,1.4,1.7,-5.7,3.4,6.7,5.8,4.4,8.2,3.7,4.3,5.3,4.8,2.2,3.8,6.1,2.3,8.8,1.7,3.3,2.1,-0.3,3.9,1,-0.6,-8.7,4.5,5.5,1.3,0,1.9,-2.7,3,1.2,2.7,7.2,4,8.4,7.4,6.5,3.4,5.7,3,5.3,7,3.7,7.8,0.9,3.5,4.4,7.3,2.5,0.4,5.6,4.6,0.8,7.3,3,3.6,4.6,1.9,1.9,3.9,1.8,3.4,1.2,1.6,-3,-1.5,3.4,2,-0.2,7.7,2.7,4.4,4.8,1.5,3.7,4.5,3.6,4.7,3.1,3.1,4.4,1,3.6,3.7,2.8,3.7,4.4,2.4,3.2,4.3,1.8,7,4.9,4.1,7.2,5.3,5.9,4.2,6.3,4.6,6,6.2,3.8,3.9,3.5,1.5,0.8,1.4,6.6,0.9,2,2.8,2.2,2,4.7,5.8,2.8,3.8,2.2,4.8,4.6,2.6,4.5,3.4,0.7,4.4,2.1,2.6,3.9,2.5,1.1,2.7,1.6,-0.5,1.1,-3,-3.6,-1,-2,2.7,-0.4,2.3,3.6,2.9,2.5,1.5,0.4,1.2,0.7,2.9,0.7,0.8,1.6,2.1,0.6,1.5,3.2,1.5,3.8,4,4.5,2.7,2.7,3.1,2,3,2,2.4,2,2.9,1.6,2.4,4.4,2.7,2.9,2.6,1.8,0.4,2.6,3.4,2.4,-6.2,-32.1,43,3.9,10.8,12.1,3,3.1,1.3,2,2.3,1,4.2,1.6
Goods,7.4,2.7,1.5,0.6,3.7,-0.4,2.7,-0.6,9.1,2.1,9.2,8,4.3,33.5,-19.5,9.1,-18.8,4.5,3.3,-1.9,9.3,-0.4,21.8,5.4,0.8,-3.3,-2.4,-0.2,4,4.3,11.6,12.9,11.7,5.7,2.9,-1.8,-0.6,-1.7,5.9,3.8,-1.4,3.4,-3.1,-9.2,1.2,7.8,8,9.6,6.5,3.2,-3.2,4.1,5.7,-2.5,-2.4,-3.7,6.2,2.6,9.2,4.8,4,3.1,6.4,3.8,3.4,4.1,1.4,9.6,8.7,9.7,-2.9,13.7,2.9,8.4,16.3,7.7,-2,5.9,-0.8,1,7.2,-1.2,1.6,13.4,6.1,10.2,-0.7,5.5,0.3,0.7,1.4,0.6,1.1,2.5,-4.3,13.5,3.3,2.6,7.2,3.8,11,7.1,12.3,9.9,-3.8,0.1,-3.9,-6.4,-1.2,1.3,-15.3,2.9,8.8,10.2,2.8,12.2,4.9,3.6,5,4.5,3,3.3,8.8,-2.2,12,0.3,4.6,-0.3,-3.3,6.8,-1.7,-2,-15.5,4.2,4.6,5.9,-3.2,4.1,-7,4.1,-0.1,2.1,8.3,2.1,12.3,9.2,9.8,5.5,9.2,0.3,6.4,6.3,3.7,11.1,-2.4,6.2,7.3,13,-0.3,-7.9,7.9,6.2,-3.5,9.8,2.1,-0.1,6.5,0.5,2.3,5.9,-1.3,5.5,-4.2,-0.9,-6.2,-3.4,2.3,2.4,-4.4,9.4,2,4.4,5.4,1.6,6.6,4.2,5.2,6.9,3.6,3.8,7.9,-2,2.7,4.9,3.8,3.2,8,2.9,4.9,5.5,-0.3,10.8,5.6,3,10.8,6.1,12.7,5,9.8,4.8,7,6.1,2.1,4.2,3.5,0.9,1.1,2.9,15.2,-0.7,1.1,5,1.6,2.2,9,11.7,3.6,4.6,1.4,5.7,5.5,3.1,6,3.9,-0.8,8.5,0.6,3.6,5.7,2.8,0.9,2.5,0.8,-6.4,-0.6,-8.1,-11.6,0.1,-2.5,7.2,-2.1,3,5.6,3,5.7,2,-1.5,0.1,2.9,5.2,-0.1,1.8,2.9,7.1,0.3,2.9,3.8,2.7,7.4,4.7,5.5,4.9,4.3,4.6,1.6,4.1,3.5,4,2.2,3.3,4.2,4.7,8.7,1.1,3.1,3.4,3.3,0,5.5,5.8,2.8,0,-10.7,55.2,0.3,25.3,11.6,-7.9,2.3,-0.1,-2.6,-0.4,-0.1,6,0.7
Durable goods,8.7,5.6,28.6,-2,2.7,7,-5.5,-7.1,39.4,20.5,16.8,16.2,3.5,134.1,-41,13.2,-46.2,-7,-1.3,2.3,8.1,-21.7,88.9,14.1,-2.3,-2.5,-10.7,-11.8,20.8,1.7,26.9,41.1,23.5,13.6,-10.1,-17.1,0.5,-6.9,13.5,7.5,-9.1,-2.7,-4.6,-24.1,-6,8.6,15.4,23.6,15.9,7.9,-17.8,13.5,9.4,-3.1,-9.7,-20.2,8.6,10.1,20.9,8.9,11.2,2.9,18.8,8.2,8.9,5,6.5,16.5,10.8,13.9,-11.7,42.8,0.6,14.4,18,20.4,-15,13.8,-0.1,-7.4,18.4,-3.2,1,27.3,8.8,19.3,-2.3,7.7,-1.1,-1.1,-1.5,-6,4.7,1.5,-24,50.3,9.4,11.1,18.2,9.5,10.5,10.7,22.9,28,-4.6,-3.5,-9,-9,2.2,2.3,-33,8.8,8,27.4,12.2,21.5,1.8,4.6,6.5,16,9.8,6,8.7,-10.2,33.3,-5.3,3.2,-4.6,-8.7,11.6,-9.9,-6.1,-36.7,19,12.7,11.9,-14.7,12.7,-25.8,13.4,1.5,3.3,19.6,4.1,32.5,16.3,21.2,16,9.6,0.1,13.6,14.6,4.8,28.2,-13.1,8.4,14.9,38.7,-6.2,-21.7,17.4,17.6,-10.4,20.3,0.1,-5.1,10.8,-1.8,5.4,9.4,-11.6,18,-12.6,-4,-10.6,-10.6,2,6.3,-6.4,16.7,2.8,8.8,8.2,3.9,13.6,4.5,10,9.9,4.4,4.3,14.8,-8,4.1,11.8,7.1,4.4,13.3,2.9,8,11.3,-1.3,19,10.6,3.3,21.8,11.8,25.8,0.9,20.5,9.9,4.9,24.3,-7.2,7,2.8,6.7,-0.3,4.7,37.7,-4.3,2.5,12.5,-3.6,0.4,19.4,18.9,5.9,7.2,1,10.7,7.8,1.9,11.1,8.1,-11.4,16.9,0.2,5.9,5.8,5.5,4.3,5,3,-12.3,-2.8,-12.8,-26.3,0.7,-2.9,20.9,-9.1,5,13.2,6.4,11.7,3.5,-2.8,3.6,9.9,10.1,0.8,5.3,9.4,10.7,1.8,3.4,4.4,6.5,15.2,7.5,7.8,7.4,8.7,5.5,2.3,5.3,4,10.4,5.7,2.5,4.6,10.6,15.8,2.5,5.5,5,1.7,-3.5,8.9,10.3,7.7,-11.3,0.4,103.6,0.6,44.7,10.6,-22,5.1,7.6,-2.8,-0.8,-1.3,16.3,0.4

In [6]:
# Transpose
t_gdp_q = gdp_q.T.reset_index()

# Inspect
t_gdp_q.head()

Year,index,Quarter,Gross domestic product,Personal consumption expenditures,Goods,Durable goods,Nondurable goods,Services,Gross private domestic investment,Fixed investment,Nonresidential,Structures,Equipment,Intellectual property products,Residential,Change in private inventories,Net exports of goods and services,Exports,Goods,Services,Imports,Goods,Services,Government consumption expenditures and gross investment,Federal,National defense,Nondefense,State and local,Addendum:,"Gross domestic product, current dollars"
0,1947,Q2,-1.1,6.8,7.4,8.7,7,5.9,-27.3,-10,-6.1,-2.1,-8.3,-4.9,-18.5,---,---,-4.9,-10.7,38.3,7.9,9.4,3.4,-0.4,-3.3,-25.2,224.5,5.7,NaN,4.7
1,1947.1,Q3,-0.8,1.3,2.7,5.6,1.9,-0.8,-11.3,13.6,-7.2,2.7,-12.8,-0.3,76.7,---,---,-18.8,-20.4,-8.4,-38.2,-43.9,-14.8,-0.1,-5,11.2,-48.5,9.4,NaN,6
2,1947.2,Q4,6.4,0.1,1.5,28.6,-5.1,-2.1,102.9,37.2,11.6,-5.6,25.3,-8,102.4,---,---,-38.2,-41,-17.2,23.5,5.5,98,-3.2,-8.6,8.9,-58.5,6.4,NaN,17.3
3,1948,Q1,6.2,2,0.6,-2,1.3,4.3,47.8,13.4,25.3,8.6,38.4,3.7,-5.1,---,---,-17,-15.5,-25.5,61.6,86.5,5.7,6.1,10.4,-4.5,113.2,-0.9,NaN,9.6
4,1948.1,Q2,6.8,4.7,3.7,2.7,4,6.4,27.1,-0.6,-12.7,11.6,-24.1,-6.1,25.3,---,---,-32.5,-34.6,-18.6,16.8,16.5,17.3,14.9,16.9,-8.7,200.7,11.4,NaN,10.7

In [7]:
# Mapping Quarters as an aribtrary month and date, reflecting the last month of GDP data.
t_gdp_q['Quarter'] = t_gdp_q['Quarter'].map({'Q1': '1-Mar', 
                                             'Q2': '1-Jun', 
                                             'Q3': '1-Sep',
                                             'Q4': '1-Dec'})

# Changing index column name to Year
t_gdp_q.rename(columns={'index': 'Year'}, inplace=True)

# Checking
t_gdp_q.head()

Year,Year,Quarter,Gross domestic product,Personal consumption expenditures,Goods,Durable goods,Nondurable goods,Services,Gross private domestic investment,Fixed investment,Nonresidential,Structures,Equipment,Intellectual property products,Residential,Change in private inventories,Net exports of goods and services,Exports,Goods,Services,Imports,Goods,Services,Government consumption expenditures and gross investment,Federal,National defense,Nondefense,State and local,Addendum:,"Gross domestic product, current dollars"
0,1947,1-Jun,-1.1,6.8,7.4,8.7,7,5.9,-27.3,-10,-6.1,-2.1,-8.3,-4.9,-18.5,---,---,-4.9,-10.7,38.3,7.9,9.4,3.4,-0.4,-3.3,-25.2,224.5,5.7,NaN,4.7
1,1947.1,1-Sep,-0.8,1.3,2.7,5.6,1.9,-0.8,-11.3,13.6,-7.2,2.7,-12.8,-0.3,76.7,---,---,-18.8,-20.4,-8.4,-38.2,-43.9,-14.8,-0.1,-5,11.2,-48.5,9.4,NaN,6
2,1947.2,1-Dec,6.4,0.1,1.5,28.6,-5.1,-2.1,102.9,37.2,11.6,-5.6,25.3,-8,102.4,---,---,-38.2,-41,-17.2,23.5,5.5,98,-3.2,-8.6,8.9,-58.5,6.4,NaN,17.3
3,1948,1-Mar,6.2,2,0.6,-2,1.3,4.3,47.8,13.4,25.3,8.6,38.4,3.7,-5.1,---,---,-17,-15.5,-25.5,61.6,86.5,5.7,6.1,10.4,-4.5,113.2,-0.9,NaN,9.6
4,1948.1,1-Jun,6.8,4.7,3.7,2.7,4,6.4,27.1,-0.6,-12.7,11.6,-24.1,-6.1,25.3,---,---,-32.5,-34.6,-18.6,16.8,16.5,17.3,14.9,16.9,-8.7,200.7,11.4,NaN,10.7

In [8]:
# Extracting just years for Year
t_gdp_q['Year'] = t_gdp_q['Year'].str[:4]

# Create 'Period' column, combining year and quarter to produce a datetime format in yyyy-mm-dd format
t_gdp_q['Period'] = pd.to_datetime(t_gdp_q['Year'].astype(int).astype(str) + '-' + t_gdp_q['Quarter'], format='%Y-%d-%b')

# Inspect
t_gdp_q.head()

Year,Year,Quarter,Gross domestic product,Personal consumption expenditures,Goods,Durable goods,Nondurable goods,Services,Gross private domestic investment,Fixed investment,Nonresidential,Structures,Equipment,Intellectual property products,Residential,Change in private inventories,Net exports of goods and services,Exports,Goods,Services,Imports,Goods,Services,Government consumption expenditures and gross investment,Federal,National defense,Nondefense,State and local,Addendum:,"Gross domestic product, current dollars",Period
0,1947,1-Jun,-1.1,6.8,7.4,8.7,7,5.9,-27.3,-10,-6.1,-2.1,-8.3,-4.9,-18.5,---,---,-4.9,-10.7,38.3,7.9,9.4,3.4,-0.4,-3.3,-25.2,224.5,5.7,NaN,4.7,1947-06-01
1,1947,1-Sep,-0.8,1.3,2.7,5.6,1.9,-0.8,-11.3,13.6,-7.2,2.7,-12.8,-0.3,76.7,---,---,-18.8,-20.4,-8.4,-38.2,-43.9,-14.8,-0.1,-5,11.2,-48.5,9.4,NaN,6,1947-09-01
2,1947,1-Dec,6.4,0.1,1.5,28.6,-5.1,-2.1,102.9,37.2,11.6,-5.6,25.3,-8,102.4,---,---,-38.2,-41,-17.2,23.5,5.5,98,-3.2,-8.6,8.9,-58.5,6.4,NaN,17.3,1947-12-01
3,1948,1-Mar,6.2,2,0.6,-2,1.3,4.3,47.8,13.4,25.3,8.6,38.4,3.7,-5.1,---,---,-17,-15.5,-25.5,61.6,86.5,5.7,6.1,10.4,-4.5,113.2,-0.9,NaN,9.6,1948-03-01
4,1948,1-Jun,6.8,4.7,3.7,2.7,4,6.4,27.1,-0.6,-12.7,11.6,-24.1,-6.1,25.3,---,---,-32.5,-34.6,-18.6,16.8,16.5,17.3,14.9,16.9,-8.7,200.7,11.4,NaN,10.7,1948-06-01

In [9]:
# Redefining gdp_qq as period and GDP only.
gdp_qq = t_gdp_q[['        Gross domestic product', 'Period']]

# Renaming column title
gdp_qq.rename(columns={'        Gross domestic product': 'gdp_q'}, inplace=True)

# Removing index name due to multi-index
gdp_qq.index.name = None

# checking
gdp_qq.head()

/var/folders/d5/f50dg_px5h73wbslkd_gnp5r0000gn/T/ipykernel_3748/3540524857.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gdp_qq.rename(columns={'        Gross domestic product': 'gdp_q'}, inplace=True)

Year gdp_q     Period
0     -1.1 1947-06-01
1     -0.8 1947-09-01
2      6.4 1947-12-01
3      6.2 1948-03-01
4      6.8 1948-06-01

In [10]:
# Inspecting
zm.data_inspector(gdp_qq)

================ Shape =================
No. of Rows: 305
No. of Columns:2

================ DTypes ================
Year
gdp_q             object
Period    datetime64[ns]
dtype: object

=============== Null Sum ===============
Year
gdp_q     0
Period    0
dtype: int64

Year gdp_q     Period
0     -1.1 1947-06-01
1     -0.8 1947-09-01
2      6.4 1947-12-01
3      6.2 1948-03-01
4      6.8 1948-06-01

In [11]:
# Setting GDP as float
gdp_qq['gdp_q'] = gdp_qq['gdp_q'].astype(float)

/var/folders/d5/f50dg_px5h73wbslkd_gnp5r0000gn/T/ipykernel_3748/275092755.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gdp_qq['gdp_q'] = gdp_qq['gdp_q'].astype(float)

In [12]:
# Inspecting
zm.data_inspector(gdp_qq)

================ Shape =================
No. of Rows: 305
No. of Columns:2

================ DTypes ================
Year
gdp_q            float64
Period    datetime64[ns]
dtype: object

=============== Null Sum ===============
Year
gdp_q     0
Period    0
dtype: int64

Year  gdp_q     Period
0      -1.1 1947-06-01
1      -0.8 1947-09-01
2       6.4 1947-12-01
3       6.2 1948-03-01
4       6.8 1948-06-01

In [22]:
# Introducing a Growth column where 1 : positive growth, 0: negative growth
gdp_qq['Growth'] = (gdp_qq['gdp_q'] > 0).astype(int)
gdp_qq.head()

/var/folders/d5/f50dg_px5h73wbslkd_gnp5r0000gn/T/ipykernel_3748/2443932436.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gdp_qq['Growth'] = (gdp_qq['gdp_q'] > 0).astype(int)

Year  gdp_q     Period  Growth
0      -1.1 1947-06-01       0
1      -0.8 1947-09-01       0
2       6.4 1947-12-01       1
3       6.2 1948-03-01       1
4       6.8 1948-06-01       1

In [13]:
# Checking for duplicates
gdp_qq[gdp_qq.duplicated()]

Empty DataFrame
Columns: [gdp_q, Period]
Index: []

##### Comment

Data appears in order.

## Monthly GDP

In [14]:
# Read in data
gdp_m = pd.read_csv('../data/monthly_gdp.csv')

In [15]:
zm.quick_check(gdp_m)

The shape is (395, 5).

,Unnamed: 0,Monthly Nominal GDP Index,Monthly Real GDP Index,Unnamed: 3,Unnamed: 4
0,1992 - Jan,6315.524,9485.623,NaN,NaN
1,1992 - Feb,6356.727,9527.945,NaN,NaN
2,1992 - Mar,6417.056,9606.173,NaN,NaN
3,1992 - Apr,6443.170,9612.231,NaN,NaN
4,1992 - May,6433.785,9594.318,NaN,NaN

In [16]:
# Renaming columns of interest
gdp_m.rename(columns={'Unnamed: 0': 'Month', 'Monthly Real GDP Index': 'real_gdp_m'}, inplace=True)

# Inspecting
gdp_m.head()

        Month  Monthly Nominal GDP Index  real_gdp_m  Unnamed: 3  Unnamed: 4
0  1992 - Jan                   6315.524    9485.623         NaN         NaN
1  1992 - Feb                   6356.727    9527.945         NaN         NaN
2  1992 - Mar                   6417.056    9606.173         NaN         NaN
3  1992 - Apr                   6443.170    9612.231         NaN         NaN
4  1992 - May                   6433.785    9594.318         NaN         NaN

In [17]:
# Creating Period column
gdp_m['Period'] = gdp_m['Month'] + ' - 01'

# Removing space, changing June and July to correct format
gdp_m['Period'] = gdp_m['Period'].str.replace(' ', '').str.replace('June', 'Jun').str.replace('July', 'Jul')

# Converting to datetime
gdp_m['Period'] = pd.to_datetime(gdp_m['Period'], format='%Y-%b-%d')

# Inspect
gdp_m.head()

,Month,Monthly Nominal GDP Index,real_gdp_m,Unnamed: 3,Unnamed: 4,Period
0,1992 - Jan,6315.524,9485.623,NaN,NaN,1992-01-01
1,1992 - Feb,6356.727,9527.945,NaN,NaN,1992-02-01
2,1992 - Mar,6417.056,9606.173,NaN,NaN,1992-03-01
3,1992 - Apr,6443.170,9612.231,NaN,NaN,1992-04-01
4,1992 - May,6433.785,9594.318,NaN,NaN,1992-05-01

In [19]:
# Re defining Df

gdp_m = gdp_m[['Period', 'real_gdp_m']]
zm.data_inspector(gdp_m)

================ Shape =================
No. of Rows: 395
No. of Columns:2

================ DTypes ================
Period        datetime64[ns]
real_gdp_m           float64
dtype: object

=============== Null Sum ===============
Period        17
real_gdp_m    17
dtype: int64

      Period  real_gdp_m
0 1992-01-01    9485.623
1 1992-02-01    9527.945
2 1992-03-01    9606.173
3 1992-04-01    9612.231
4 1992-05-01    9594.318

In [20]:
# Applying .pct_change to gdp_m * 100 to be on similar annualised percentage scale as gdp_q
gdp_m['real_gdp_m'] = (gdp_m['real_gdp_m'].pct_change() * 100)

# Drop NaN
gdp_m = gdp_m.dropna()

# Inspect
gdp_m.head(10)

/var/folders/d5/f50dg_px5h73wbslkd_gnp5r0000gn/T/ipykernel_3748/2669447353.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gdp_m['real_gdp_m'] = (gdp_m['real_gdp_m'].pct_change() * 100)

       Period  real_gdp_m
1  1992-02-01    0.446170
2  1992-03-01    0.821037
3  1992-04-01    0.063064
4  1992-05-01   -0.186356
5  1992-06-01    1.346099
6  1992-07-01    0.168541
7  1992-08-01   -0.192837
8  1992-09-01    0.348912
9  1992-10-01    0.561887
10 1992-11-01    0.280087

In [24]:
# Introducing a Growth column where 1 : positive growth, 0: negative growth
gdp_m['Growth'] = (gdp_m['real_gdp_m'] > 0).astype(int)
gdp_m.head()

      Period  real_gdp_m  Growth
1 1992-02-01    0.446170       1
2 1992-03-01    0.821037       1
3 1992-04-01    0.063064       1
4 1992-05-01   -0.186356       0
5 1992-06-01    1.346099       1

In [26]:
testq = gdp_qq
testm = gdp_m

In [27]:
testm.head()

      Period  real_gdp_m  Growth
1 1992-02-01    0.446170       1
2 1992-03-01    0.821037       1
3 1992-04-01    0.063064       1
4 1992-05-01   -0.186356       0
5 1992-06-01    1.346099       1

In [28]:
testq.head()

Year  gdp_q     Period  Growth
0      -1.1 1947-06-01       0
1      -0.8 1947-09-01       0
2       6.4 1947-12-01       1
3       6.2 1948-03-01       1
4       6.8 1948-06-01       1

In [29]:
testq['Period'] = testq['Period'] + pd.offsets.MonthEnd()
testq.head()

/var/folders/d5/f50dg_px5h73wbslkd_gnp5r0000gn/T/ipykernel_3748/2207332425.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  testq['Period'] = testq['Period'] + pd.offsets.MonthEnd()

Year  gdp_q     Period  Growth
0      -1.1 1947-06-30       0
1      -0.8 1947-09-30       0
2       6.4 1947-12-31       1
3       6.2 1948-03-31       1
4       6.8 1948-06-30       1

In [30]:
testq.set_index('Period', inplace=True)
testm.set_index('Period', inplace=True)

In [31]:
testq.head()

Year        gdp_q  Growth
Period
1947-06-30   -1.1       0
1947-09-30   -0.8       0
1947-12-31    6.4       1
1948-03-31    6.2       1
1948-06-30    6.8       1

In [32]:
testm.head()

            real_gdp_m  Growth
Period
1992-02-01    0.446170       1
1992-03-01    0.821037       1
1992-04-01    0.063064       1
1992-05-01   -0.186356       0
1992-06-01    1.346099       1

In [33]:
testm = testm.resample('Q').mean()
testm.head()

            real_gdp_m    Growth
Period
1992-03-31    0.633604  1.000000
1992-06-30    0.407602  0.666667
1992-09-30    0.108205  0.666667
1992-12-31    0.403100  1.000000
1993-03-31   -0.122668  0.333333

In [34]:
testm['Growth'] = (testm['real_gdp_m'] > 0).astype(int)
testm.head()

            real_gdp_m  Growth
Period
1992-03-31    0.633604       1
1992-06-30    0.407602       1
1992-09-30    0.108205       1
1992-12-31    0.403100       1
1993-03-31   -0.122668       0

In [40]:
test = testq.join(testm, lsuffix='_left', rsuffix='_right')
test = test.dropna()
test.head()

            gdp_q  Growth_left  real_gdp_m  Growth_right
Period
1992-03-31    4.9            1    0.633604           1.0
1992-06-30    4.4            1    0.407602           1.0
1992-09-30    4.0            1    0.108205           1.0
1992-12-31    4.2            1    0.403100           1.0
1993-03-31    0.7            1   -0.122668           0.0

In [36]:
import numpy as np
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

In [43]:
real_mape = np.mean(np.abs((np.array(test['Growth_left']) - np.array(test['Growth_right'])) / np.array(test['Growth_left']))) * 100
real_mape

/var/folders/d5/f50dg_px5h73wbslkd_gnp5r0000gn/T/ipykernel_3748/3833489069.py:1: RuntimeWarning: divide by zero encountered in divide
  real_mape = np.mean(np.abs((np.array(test['Growth_left']) - np.array(test['Growth_right'])) / np.array(test['Growth_left']))) * 100
/var/folders/d5/f50dg_px5h73wbslkd_gnp5r0000gn/T/ipykernel_3748/3833489069.py:1: RuntimeWarning: invalid value encountered in divide
  real_mape = np.mean(np.abs((np.array(test['Growth_left']) - np.array(test['Growth_right'])) / np.array(test['Growth_left']))) * 100

nan

In [48]:
(((test['Growth_left'] - test['Growth_right']) ** 2) / len(test['Growth_left'])).mean() ** 0.5

0.02969569354582493

In [44]:
# Assuming 'Growth_left' and 'Growth_right' are the correct column names
left_values = np.array(test['Growth_left'])
right_values = np.array(test['Growth_right'])

# Calculate MAPE, handling division by zero and ignoring NaN values
mape_values = np.abs((left_values - right_values) / np.where(left_values == 0, 1, left_values))
mape_values = mape_values[~np.isnan(mape_values)]  # Remove NaN values

# Calculate the mean MAPE
real_mape = np.mean(mape_values) * 100
real_mape

11.11111111111111

##### Comment

Dataframes of interest:

1. gdp_qq
2.

# End of Notebook

Please [click here]() to proceed to the next notebook. o

Feel free to click on the following notebooks to 'fast forward' to other sections of this project.

|Notebook Title|Description|
|---|---|
|[01_Intro_Data_Cleaning](01_Intro_Data_Cleaning.ipynb)|This notebook contains the introduction of the project, background motivation, problem statement and the inspection and cleaning of data.|